---
- name: Install jsondiff Python library
  when: inventory_hostname == groups['managers'][0]
  ansible.builtin.pip:
    name: jsondiff==2.0.0

- name: Install pyyaml Python library
  when: inventory_hostname == groups['managers'][0]
  ansible.builtin.pip:
    name: pyyaml==6.0

- name: Check if Swarm has already been initialized
  ansible.builtin.shell: docker node ls
  register: swarm_status
  ignore_errors: true

- name: Initialize new Docker Swarm Leader
  ansible.builtin.shell: docker swarm init --advertise-addr={{ inventory_hostname }}
  when: swarm_status.rc != 0 and inventory_hostname == groups['managers'][0]
  run_once: true

- name: Get Manager join token
  ansible.builtin.shell: docker swarm join-token --quiet manager
  when: inventory_hostname == groups['managers'][0]
  register: manager_token

- name: Get Worker join token
  ansible.builtin.shell: docker swarm join-token --quiet worker
  when: inventory_hostname == groups['managers'][0]
  register: worker_token