FROM node:16-alpine AS builder

ENV NODE_ENV production

# Add a work directory
WORKDIR /app

# Cache and Install dependencies
COPY package.json .

RUN yarn install --production

# Copy app files
COPY . .

ARG DOMAIN

ENV REACT_APP_API_URL $DOMAIN

# Build the app
RUN yarn build

# Bundle static assets with nginx
FROM nginx:1.22.0-alpine as production

ENV NODE_ENV production

# Copy built assets from builder
COPY --from=builder /app/build /usr/share/nginx/html

# Add your nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port
EXPOSE 3000

# Start nginx
CMD ["nginx", "-g", "daemon off;"]